# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev9+g8153adf.d20230622'
__version_tuple__ = version_tuple = (0, 1, 'dev9', 'g8153adf.d20230622')
