# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev20+g5fd1773.d20230627'
__version_tuple__ = version_tuple = (0, 1, 'dev20', 'g5fd1773.d20230627')
